### ISSUE TITLE
CreateCanvas2d() Fails in Server-Side Blazor Apps

### ISSUE THREAD

**Issue by sparkie108** [BlazorExtensions/Canvas#12]
**Issue**
When trying to call `this._context = this._canvasReference.CreateCanvas2d();` in a server-side Blazor app you get the following exception:
`
Unable to cast object of type 'Microsoft.AspNetCore.Blazor.Server.Circuits.RemoteJSRuntime' to type 'Microsoft.JSInterop.IJSInProcessRuntime'.
`

It seems related to the "Calling JavaScript from .NET" section of:
[Blazor 0.5.0 experimental release now available](https://blogs.msdn.microsoft.com/webdev/2018/07/25/blazor-0-5-0-experimental-release-now-available/).

**To Reproduce**
It happens when you try the Sample in a server-side Blazor app.

**Comment by galvesribeiro** [comment]
Hello @sparkie108 

That happens because server-side Blazor requires that all JS interop being async. 

The current Canvas implementation isn't async so it will not work. It was meant to be used on the client-side Blazor.

We can make that work but before that, there is a work on batch rendering that must be done so the performance isn't affected.

I've opened #13 to get track of it and for now, there is nothing we can do to allow server-side rendering to work.

Please follow up on that issue as I'm closing this for now.

Thanks!

**Comment by ctrl-alt-d** [comment]
I miss a little 'warning' on read.me page informing tabout his limitation.

**Comment by galvesribeiro** [comment]
Not yet. 

I'll probably wait for #20 to get in. It is adding WebGL to the table and (if required) will change the API surface a bit.

Once it is done, I'll then move forward with #13 which will add async methods and as a side-effect enable server-side mode.

Use Canvas remotely with server-side where you don't have batch rendering will probably give a very poor performance.
