### ISSUE TITLE
This doesn't seem to support the current released Blazor esp Client Side

### ISSUE THREAD

**Issue by dbowser** [BlazorExtensions/Canvas#29]
The example uses addTagHelper which is not supported among other issues to get it to compile.
However, after figuring out how to get it to compile without warnings my call: 
' this._context = await this._canvasRef.CreateCanvas2DAsync();' 
created an 'unhandled exception rendering component ':
Microsoft.JSInterop.JSException: t.getContext is not a function'

**Comment by vanjavk** [comment]
yeah it doesn't

**Comment by chucker** [comment]
I can't reproduce the `Microsoft.JSInterop.JSException: t.getContext is not a function` error, but I've addressed two issues with the readme.

You can disregard the `_ViewImports.cshtml`  / `addTagHelper` part altogether.

Also, be careful to use `@ref` now instead of `ref`. The latter will silently do the wrong thing (starting with preview 6).
